# Generated by Django 6.0.1 on 2026-01-20 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('CHF', 'Swiss Franc'), ('GBP', 'British Pound')], default='EUR', help_text='Default currency for displaying aggregated wealth', max_length=3)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('sync_frequency_hours', models.PositiveIntegerField(default=24)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
