# Generated by Django 6.0.1 on 2026-01-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='send_daily_report',
            field=models.BooleanField(default=False, help_text='Send daily wealth summary email'),
        ),
    ]
