# Generated by Django 6.0.1 on 2026-02-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_to_weekly_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_chart_granularity',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', help_text='Default granularity for wealth chart', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_chart_range',
            field=models.IntegerField(choices=[(30, '30 days'), (90, '90 days'), (180, '6 months'), (365, '1 year'), (730, '2 years'), (3650, 'All')], default=365, help_text='Default time range for wealth chart'),
        ),
    ]
