# Generated by Django 6.0.1 on 2026-01-20 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-defined account name', max_length=100)),
                ('account_identifier', models.CharField(blank=True, help_text='IBAN, account number, or external ID', max_length=100)),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('brokerage', 'Brokerage/Investment Account'), ('retirement', 'Retirement Account'), ('crypto', 'Cryptocurrency Account'), ('other', 'Other')], default='checking', max_length=20)),
                ('currency', models.CharField(default='EUR', help_text='Native currency of the account', max_length=3)),
                ('encrypted_credentials', models.BinaryField(blank=True, null=True)),
                ('is_manual', models.BooleanField(default=False, help_text='Manual account without automated sync')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Sync Error'), ('pending_auth', 'Pending Authentication')], default='pending_auth', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('pending_auth_state', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='brokers.broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_accounts',
                'ordering': ['broker__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, help_text='Account balance in native currency', max_digits=20)),
                ('currency', models.CharField(help_text='Currency of the balance', max_length=3)),
                ('balance_base_currency', models.DecimalField(blank=True, decimal_places=4, help_text='Balance converted to user base currency', max_digits=20, null=True)),
                ('base_currency', models.CharField(blank=True, help_text='User base currency at time of snapshot', max_length=3)),
                ('exchange_rate_used', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('snapshot_date', models.DateField(help_text='Date the balance was valid for')),
                ('snapshot_source', models.CharField(choices=[('auto', 'Automatic Sync'), ('manual', 'Manual Entry'), ('import', 'Data Import')], default='auto', max_length=20)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.financialaccount')),
            ],
            options={
                'db_table': 'account_snapshots',
                'ordering': ['-snapshot_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('isin', models.CharField(blank=True, max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('asset_class', models.CharField(choices=[('equity', 'Equity/Stocks'), ('fixed_income', 'Fixed Income/Bonds'), ('cash', 'Cash & Equivalents'), ('real_estate', 'Real Estate'), ('commodity', 'Commodities'), ('crypto', 'Cryptocurrency'), ('other', 'Other')], default='other', max_length=50)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.accountsnapshot')),
            ],
            options={
                'db_table': 'portfolio_positions',
            },
        ),
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['account', 'snapshot_date'], name='account_sna_account_0b9c10_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsnapshot',
            index=models.Index(fields=['snapshot_date'], name='account_sna_snapsho_ed7b80_idx'),
        ),
    ]
