# Generated by Django 6.0.1 on 2026-01-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('rate_date', models.DateField()),
                ('source', models.CharField(default='frankfurter', help_text='Data source (frankfurter, manual, etc.)', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exchange_rates',
                'indexes': [models.Index(fields=['rate_date'], name='exchange_ra_rate_da_c4d95f_idx'), models.Index(fields=['from_currency', 'to_currency', 'rate_date'], name='exchange_ra_from_cu_bd9591_idx')],
                'unique_together': {('from_currency', 'to_currency', 'rate_date')},
            },
        ),
    ]
