# Generated by Django 6.0.1 on 2026-01-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal broker identifier (e.g., dkb, commerzbank)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('integration_type', models.CharField(choices=[('fints', 'FinTS Protocol'), ('rest', 'REST API'), ('graphql', 'GraphQL API')], max_length=20)),
                ('bank_identifier', models.CharField(blank=True, help_text='BLZ for German banks', max_length=20)),
                ('fints_server', models.URLField(blank=True, help_text='FinTS server URL')),
                ('api_base_url', models.URLField(blank=True, help_text='Base URL for REST/GraphQL APIs')),
                ('logo_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('country', models.CharField(default='DE', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_2fa', models.BooleanField(default=False)),
                ('credential_schema', models.JSONField(default=dict, help_text='JSON schema defining required credential fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brokers',
                'ordering': ['name'],
            },
        ),
    ]
