# Generated by Django 6.0.1 on 2026-01-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='supports_auto_sync',
            field=models.BooleanField(default=False, help_text='Whether accounts can be synced automatically without user interaction (e.g., decoupled TAN)'),
        ),
    ]
