"""
Test script to explore Morgan Stanley JWT token endpoints.

This script attempts to identify how the frontend obtains JWT tokens after login.
The JWT is needed for GraphQL API calls but isn't returned directly in the login response.

Key observations:
- The dashboard HTML contains `SW.initialData` with `apiKey` which matches JWT's `ses` claim
- The JWT is generated by frontend JavaScript, not returned in login response
- There must be an endpoint or mechanism to obtain the JWT

Run: python -m backend.brokers.integrations.test_ms_jwt
"""
import os
import re
import json
import sys

# Add project root to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))

from curl_cffi import requests as curl_requests


def test_jwt_endpoints():
    """Test various potential endpoints that might return JWT tokens."""

    # You need to provide these from a valid login session
    # Get cookies from browser DevTools after logging in
    print("=" * 60)
    print("Morgan Stanley JWT Token Endpoint Investigation")
    print("=" * 60)
    print()
    print("This script tests potential endpoints that might return JWT tokens.")
    print("You need to provide valid session cookies from a logged-in browser session.")
    print()

    # Check if we have test cookies in environment
    jsessionid = os.environ.get('MS_JSESSIONID')
    if not jsessionid:
        print("ERROR: Set MS_JSESSIONID environment variable with your session cookie value.")
        print("Example: export MS_JSESSIONID='eG3X6bY6...'")
        return

    base_url = "https://atwork.morganstanley.com"

    session = curl_requests.Session(impersonate="chrome")
    session.cookies.set('JSESSIONID', jsessionid, domain='atwork.morganstanley.com')

    # Add any other cookies if provided
    other_cookies = os.environ.get('MS_OTHER_COOKIES', '')
    if other_cookies:
        for cookie in other_cookies.split(';'):
            if '=' in cookie:
                name, value = cookie.strip().split('=', 1)
                session.cookies.set(name, value, domain='atwork.morganstanley.com')

    # List of potential endpoints to test
    test_endpoints = [
        # Direct token endpoints
        ('GET', '/solium/api/auth/token'),
        ('GET', '/solium/api/session/token'),
        ('GET', '/api/auth/token'),
        ('GET', '/api/v1/auth/token'),
        ('POST', '/solium/api/auth/token'),
        ('POST', '/api/auth/token'),

        # Session endpoints
        ('GET', '/solium/api/session'),
        ('GET', '/solium/api/auth/session'),
        ('GET', '/api/session'),

        # Mobile/API endpoints (sometimes return tokens)
        ('GET', '/solium/servlet/mobileAuth.do'),
        ('GET', '/solium/servlet/apiAuth.do'),
        ('GET', '/solium/servlet/getToken.do'),
        ('GET', '/solium/servlet/apiToken.do'),

        # OAuth endpoints
        ('GET', '/oauth/token'),
        ('POST', '/oauth/token'),
        ('GET', '/oauth2/token'),

        # User/participant endpoints
        ('GET', '/solium/servlet/getParticipantSummary.do'),
        ('GET', '/solium/api/participant/summary'),
        ('GET', '/solium/api/user/info'),
        ('GET', '/solium/api/me'),

        # GraphQL (try without auth to see error)
        ('POST', '/graphql'),
    ]

    headers_base = {
        'Accept': 'application/json, text/html, */*',
        'Accept-Language': 'en-US,en;q=0.9',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
        'Origin': base_url,
        'Referer': f'{base_url}/solium/servlet/ui',
    }

    print(f"Testing with JSESSIONID: {jsessionid[:20]}...")
    print()

    for method, endpoint in test_endpoints:
        try:
            url = f"{base_url}{endpoint}"
            headers = headers_base.copy()

            if method == 'POST':
                headers['Content-Type'] = 'application/json'
                if 'graphql' in endpoint:
                    # Test a simple query
                    response = session.post(
                        url,
                        json={'query': '{ __typename }'},
                        headers=headers,
                        timeout=10
                    )
                else:
                    response = session.post(url, json={}, headers=headers, timeout=10)
            else:
                response = session.get(url, headers=headers, timeout=10)

            status = response.status_code
            content_type = response.headers.get('content-type', 'unknown')

            # Check for JWT in response
            jwt_found = False
            jwt_location = None

            # Check headers
            for header in ['authorization', 'Authorization', 'x-auth-token', 'X-Auth-Token']:
                if header in response.headers:
                    value = response.headers[header]
                    if value.startswith('eyJ') or value.startswith('Bearer eyJ'):
                        jwt_found = True
                        jwt_location = f'header:{header}'
                        break

            # Check body for JWT pattern
            if not jwt_found and response.text:
                jwt_match = re.search(r'eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+', response.text)
                if jwt_match:
                    jwt_found = True
                    jwt_location = 'body'

            # Status indicator
            status_indicator = "✓" if status == 200 else "✗"
            jwt_indicator = "🔑 JWT FOUND!" if jwt_found else ""

            print(f"{status_indicator} {method:4} {endpoint:50} [{status}] {content_type[:30]:30} {jwt_indicator}")

            if jwt_found:
                print(f"   → JWT location: {jwt_location}")
                if jwt_location == 'body':
                    jwt_token = jwt_match.group(0)
                    print(f"   → Token preview: {jwt_token[:50]}...")
                    # Try to decode and show claims
                    try:
                        import base64
                        parts = jwt_token.split('.')
                        if len(parts) >= 2:
                            payload = parts[1]
                            padding = 4 - len(payload) % 4
                            if padding != 4:
                                payload += '=' * padding
                            decoded = base64.urlsafe_b64decode(payload)
                            claims = json.loads(decoded)
                            print(f"   → Claims: {list(claims.keys())}")
                    except:
                        pass

            # If JSON response, show keys
            if status == 200 and 'json' in content_type.lower():
                try:
                    data = response.json()
                    if isinstance(data, dict):
                        keys = list(data.keys())[:10]
                        print(f"   → JSON keys: {keys}")
                except:
                    pass

        except Exception as e:
            print(f"✗ {method:4} {endpoint:50} ERROR: {str(e)[:40]}")

    print()
    print("=" * 60)
    print("Next steps:")
    print("1. If JWT found, update integration to use that endpoint")
    print("2. Check browser Network tab to see how frontend gets JWT")
    print("3. Look at JS bundles for token generation logic")
    print("=" * 60)


def analyze_dashboard_html():
    """Analyze dashboard HTML to understand JWT generation."""
    print()
    print("=" * 60)
    print("Dashboard HTML Analysis Tips")
    print("=" * 60)
    print()
    print("Key data to look for in browser DevTools:")
    print()
    print("1. SW.initialData object contains:")
    print("   - apiKey: session ID (matches JWT 'ses' claim)")
    print("   - activeAccount.employeePK: for employeeid header")
    print("   - activeAccount.accountPK: JWT 'sub' claim")
    print()
    print("2. Network tab - look for requests containing JWT:")
    print("   - Filter by 'token' or 'auth'")
    print("   - Check XHR requests after page load")
    print("   - Look for WebSocket messages")
    print()
    print("3. Application tab > Local/Session Storage:")
    print("   - JWT might be stored in browser storage")
    print()
    print("4. Console - try these commands:")
    print("   - SW.initialData")
    print("   - localStorage.getItem('token')")
    print("   - sessionStorage.getItem('token')")
    print()


def test_graphql_auth_mutations():
    """Test GraphQL mutations that might return authentication tokens."""
    print()
    print("=" * 60)
    print("Testing GraphQL Authentication Mutations")
    print("=" * 60)
    print()

    jsessionid = os.environ.get('MS_JSESSIONID')
    if not jsessionid:
        print("ERROR: Set MS_JSESSIONID environment variable")
        return

    base_url = "https://atwork.morganstanley.com"
    session = curl_requests.Session(impersonate="chrome")
    session.cookies.set('JSESSIONID', jsessionid, domain='atwork.morganstanley.com')

    headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'Origin': base_url,
        'Referer': f'{base_url}/solium/servlet/ui',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
    }

    # Try various GraphQL auth queries/mutations
    queries = [
        # Try to get auth token
        ('getToken', '{ getToken { token } }'),
        ('getAuthToken', '{ getAuthToken { token } }'),
        ('authenticate', '{ authenticate { token } }'),
        ('login', 'mutation { login { token } }'),
        ('session', '{ session { token } }'),
        ('viewer', '{ viewer { id token } }'),
        ('me', '{ me { id token } }'),
        ('currentUser', '{ currentUser { id token } }'),

        # Introspection to see available queries
        ('introspection', '{ __schema { queryType { name fields { name } } mutationType { name fields { name } } } }'),

        # Check what's in the schema
        ('types', '{ __schema { types { name kind } } }'),
    ]

    for name, query in queries:
        try:
            response = session.post(
                f"{base_url}/graphql",
                json={'query': query},
                headers=headers,
                timeout=10
            )
            status = response.status_code
            print(f"[{status}] {name}")

            if status == 200:
                try:
                    data = response.json()
                    if 'errors' in data:
                        errors = data['errors']
                        if errors:
                            msg = errors[0].get('message', '')[:60]
                            print(f"   → Error: {msg}")
                    elif 'data' in data:
                        result = data['data']
                        if result:
                            print(f"   → Data: {str(result)[:100]}")
                            # Check for JWT in result
                            result_str = json.dumps(result)
                            if 'eyJ' in result_str:
                                print("   → 🔑 JWT FOUND in response!")
                except:
                    pass

        except Exception as e:
            print(f"[ERR] {name}: {str(e)[:40]}")


def test_token_with_api_key():
    """Test if apiKey from SW.initialData can be exchanged for JWT."""
    print()
    print("=" * 60)
    print("Testing Token Exchange with API Key")
    print("=" * 60)
    print()

    jsessionid = os.environ.get('MS_JSESSIONID')
    api_key = os.environ.get('MS_API_KEY')  # From SW.initialData.apiKey

    if not jsessionid:
        print("ERROR: Set MS_JSESSIONID environment variable")
        return
    if not api_key:
        print("INFO: Set MS_API_KEY (from SW.initialData.apiKey) for more tests")
        print("      This is the session ID that matches JWT's 'ses' claim")
        print()

    base_url = "https://atwork.morganstanley.com"
    session = curl_requests.Session(impersonate="chrome")
    session.cookies.set('JSESSIONID', jsessionid, domain='atwork.morganstanley.com')

    if api_key:
        # Try endpoints that might accept apiKey
        endpoints = [
            ('GET', f'/solium/api/auth/token?apiKey={api_key}'),
            ('GET', f'/solium/api/token?sessionId={api_key}'),
            ('POST', '/solium/api/auth/token', {'apiKey': api_key}),
            ('POST', '/solium/api/auth/token', {'sessionId': api_key}),
            ('POST', '/api/auth/token', {'sessionId': api_key}),
        ]

        headers = {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'Origin': base_url,
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
        }

        for endpoint_info in endpoints:
            method = endpoint_info[0]
            endpoint = endpoint_info[1]
            body = endpoint_info[2] if len(endpoint_info) > 2 else None

            try:
                if method == 'POST':
                    response = session.post(
                        f"{base_url}{endpoint}",
                        json=body,
                        headers=headers,
                        timeout=10
                    )
                else:
                    response = session.get(
                        f"{base_url}{endpoint}",
                        headers=headers,
                        timeout=10
                    )

                status = response.status_code
                print(f"[{status}] {method} {endpoint}")

                if status == 200:
                    # Check for JWT
                    if 'eyJ' in response.text:
                        print("   → 🔑 JWT FOUND!")
                        jwt_match = re.search(r'eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+', response.text)
                        if jwt_match:
                            print(f"   → Token: {jwt_match.group(0)[:50]}...")

            except Exception as e:
                print(f"[ERR] {method} {endpoint}: {str(e)[:40]}")


def extract_sw_initial_data():
    """Fetch dashboard and extract SW.initialData to look for token info."""
    print()
    print("=" * 60)
    print("Extracting SW.initialData from Dashboard")
    print("=" * 60)
    print()

    jsessionid = os.environ.get('MS_JSESSIONID')
    if not jsessionid:
        print("ERROR: Set MS_JSESSIONID environment variable")
        return

    base_url = "https://atwork.morganstanley.com"
    session = curl_requests.Session(impersonate="chrome")
    session.cookies.set('JSESSIONID', jsessionid, domain='atwork.morganstanley.com')

    try:
        response = session.get(
            f"{base_url}/solium/servlet/ui",
            headers={
                'Accept': 'text/html',
                'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
            },
            timeout=30
        )

        if 'userLogin' in response.url:
            print("Session expired - redirected to login page")
            return

        print(f"Dashboard fetched: {len(response.text)} bytes")
        print()

        # Extract SW.initialData
        sw_match = re.search(r'SW\.initialData\s*=\s*(\{.*?\});', response.text, re.DOTALL)
        if sw_match:
            try:
                # Parse the JavaScript object (may need some cleanup)
                js_obj = sw_match.group(1)
                # Try to parse as JSON (may fail if it has JS-specific syntax)
                print("Found SW.initialData. Looking for token-related fields...")
                print()

                # Look for specific patterns
                patterns = [
                    (r"apiKey:\s*'([^']+)'", 'apiKey'),
                    (r"employeePK:\s*'([^']+)'", 'employeePK'),
                    (r"accountPK:\s*'([^']+)'", 'accountPK'),
                    (r"token:\s*'([^']+)'", 'token'),
                    (r"jwt:\s*'([^']+)'", 'jwt'),
                    (r"authToken:\s*'([^']+)'", 'authToken'),
                    (r"accessToken:\s*'([^']+)'", 'accessToken'),
                    (r"authorization:\s*'([^']+)'", 'authorization'),
                ]

                for pattern, name in patterns:
                    match = re.search(pattern, js_obj)
                    if match:
                        value = match.group(1)
                        is_jwt = value.startswith('eyJ')
                        indicator = "🔑 JWT!" if is_jwt else ""
                        print(f"  {name}: {value[:50]}... {indicator}")

                # Also look for any JWT in the full page
                jwt_matches = re.findall(r'eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+', response.text)
                if jwt_matches:
                    print()
                    print(f"Found {len(jwt_matches)} JWT-like strings in page")
                    for i, jwt in enumerate(jwt_matches[:3]):
                        print(f"  JWT {i+1}: {jwt[:60]}...")

            except Exception as e:
                print(f"Error parsing SW.initialData: {e}")
        else:
            print("SW.initialData not found in page")

            # Look for any JWT anyway
            jwt_matches = re.findall(r'eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+', response.text)
            if jwt_matches:
                print()
                print(f"Found {len(jwt_matches)} JWT-like strings in page")
                for i, jwt in enumerate(jwt_matches[:3]):
                    print(f"  JWT {i+1}: {jwt[:60]}...")

    except Exception as e:
        print(f"Error fetching dashboard: {e}")


if __name__ == '__main__':
    analyze_dashboard_html()
    extract_sw_initial_data()
    test_graphql_auth_mutations()
    test_token_with_api_key()
    test_jwt_endpoints()
